In [31]:
#import libraries
import pandas as pd
import json
import os

In [32]:
# 1. Load both files
ledger = pd.read_csv('ledger.csv')
gateway = pd.read_csv('gateway.csv')

In [52]:
# 2. Check duplicates and null
print('Duplicates in ledger:')
ledger.duplicated().sum()
print('Duplicates in gateway:')
gateway.duplicated().sum()

Duplicates in ledger:
Duplicates in gateway:

np.int64(0)

In [51]:
# Check for null values
print('Null values in ledger:')
display(ledger.isnull().sum())

print('\nNull values in gateway:')
display(gateway.isnull().sum())

Null values in ledger:

transaction_id      0
transaction_date    0
merchant_id         0
amount_usd          0
status              0
payment_method      0
dtype: int64

Null values in gateway:

transaction_id      0
transaction_date    0
merchant_id         0
amount_usd          0
status              0
payment_method      0
dtype: int64

In [57]:
# 3. identify records missing in gateway
display(missing_in_gateway)

,transaction_id,transaction_date_ledger,merchant_id_ledger,amount_usd_ledger,status_ledger,payment_method_ledger,transaction_date_gateway,merchant_id_gateway,amount_usd_gateway,status_gateway,payment_method_gateway,_merge
3,R004,2026-03-02,M003,2100.0,success,Card,NaN,NaN,NaN,NaN,NaN,left_only
9,R010,2026-03-05,M004,2500.0,success,Wallet,NaN,NaN,NaN,NaN,NaN,left_only

In [58]:
# 4. identify records missing in ledger
display(missing_in_ledger)

,transaction_id,transaction_date_ledger,merchant_id_ledger,amount_usd_ledger,status_ledger,payment_method_ledger,transaction_date_gateway,merchant_id_gateway,amount_usd_gateway,status_gateway,payment_method_gateway,_merge
10,R011,NaN,NaN,NaN,NaN,NaN,05-03-2026,M003,1800.0,success,Card,right_only

In [60]:
# 5. Identify amount mismatches
display(amount_mismatches)

,transaction_id,transaction_date_ledger,merchant_id_ledger,amount_usd_ledger,status_ledger,payment_method_ledger,transaction_date_gateway,merchant_id_gateway,amount_usd_gateway,status_gateway,payment_method_gateway,_merge
1,R002,2026-03-01,M002,850.0,success,Card,01-03-2026,M002,900.0,success,Card,both
7,R008,2026-03-04,M001,640.0,success,Card,04-03-2026,M001,600.0,success,Card,both

In [61]:
# 6. identify status mismatches
display(status_mismatches)

,transaction_id,transaction_date_ledger,merchant_id_ledger,amount_usd_ledger,status_ledger,payment_method_ledger,transaction_date_gateway,merchant_id_gateway,amount_usd_gateway,status_gateway,payment_method_gateway,_merge
4,R005,2026-03-03,M004,7200.0,success,Card,03-03-2026,M004,7200.0,failed,Card,both

In [65]:
# 7. build a final reconciliation report
display(reconciliation_report)

,transaction_id,transaction_date_ledger,merchant_id_ledger,amount_usd_ledger,status_ledger,payment_method_ledger,transaction_date_gateway,merchant_id_gateway,amount_usd_gateway,status_gateway,payment_method_gateway,_merge,recon_status
0,R001,2026-03-01,M001,1200.0,success,UPI,01-03-2026,M001,1200.0,success,UPI,both,Matched
1,R002,2026-03-01,M002,850.0,success,Card,01-03-2026,M002,900.0,success,Card,both,Amount Mismatch
2,R003,2026-03-02,M001,500.0,success,Wallet,02-03-2026,M001,500.0,success,Wallet,both,Matched
3,R004,2026-03-02,M003,2100.0,success,Card,NaN,NaN,NaN,NaN,NaN,left_only,Missing in Gateway
4,R005,2026-03-03,M004,7200.0,success,Card,03-03-2026,M004,7200.0,failed,Card,both,Status Mismatch
5,R006,2026-03-03,M002,950.0,success,UPI,03-03-2026,M002,950.0,success,UPI,both,Matched
6,R007,2026-03-04,M005,3300.0,failed,NetBanking,04-03-2026,M005,3300.0,failed,NetBanking,both,Matched
7,R008,2026-03-04,M001,640.0,success,Card,04-03-2026,M001,600.0,success,Card,both,Amount Mismatch
8,R009,2026-03-05,M002,4100.0,success,Card,05-03-2026,M002,4100.0,success,Card,both,Matched
9,R010,2026-03-05,M004,2500.0,success,Wallet,NaN,NaN,NaN,NaN,NaN,left_only,Missing in Gateway
10,R011,NaN,NaN,NaN,NaN,NaN,05-03-2026,M003,1800.0,success,Card,right_only,Missing in Ledger

## Summary Metrics

In [66]:
# 8. generate summary metrics
display(summary)

{'total_ledger_records': 10,
 'total_gateway_records': 9,
 'ledger_duplicates': 0,
 'gateway_duplicates': 0,
 'ledger_nulls': 0,
 'gateway_nulls': 0,
 'missing_in_gateway': 2,
 'missing_in_ledger': 1,
 'amount_mismatches': 2,
 'status_mismatches': 1,
 'perfect_matches': 5}